package com.model;

/**
 * TToujijianli generated by MyEclipse Persistence Tools
 */

public class TToujijianli implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer zhaopinId;

	private Integer userId;

	private String toudishijian;

	private String del;

	// Constructors

	/** default constructor */
	public TToujijianli()
	{
	}

	/** full constructor */
	public TToujijianli(Integer zhaopinId, Integer userId, String toudishijian,
			String del)
	{
		this.zhaopinId = zhaopinId;
		this.userId = userId;
		this.toudishijian = toudishijian;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getZhaopinId()
	{
		return this.zhaopinId;
	}

	public void setZhaopinId(Integer zhaopinId)
	{
		this.zhaopinId = zhaopinId;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public String getToudishijian()
	{
		return this.toudishijian;
	}

	public void setToudishijian(String toudishijian)
	{
		this.toudishijian = toudishijian;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}